# COSAI BEGIN BLOCK
KERNWARNFLAGS ?= -Werror
# COSAI END BLOCK -

not-y := n
not-n := y
m-not-y := n
m-not-n := m

# The original Intel build selected the card-side build only when the
# proprietary CONFIG_X86_VCAPCI kernel option was set.  Distribution kernels
# do not carry that option, so package role must be explicit.
#
#   VCA_BUILD_ROLE=host  - modules loaded on the PCIe host
#   VCA_BUILD_ROLE=node  - modules loaded inside a VCA node OS
VCA_BUILD_ROLE ?= host
ifneq ($(VCA_BUILD_ROLE),$(firstword $(filter host node,$(VCA_BUILD_ROLE))))
$(error $$(VCA_BUILD_ROLE) must be host or node)
endif
ifneq ($(VCA_CARD_ARCH),$(firstword $(filter l1om k1om,$(VCA_CARD_ARCH))))
$(error $$(VCA_CARD_ARCH) must be l1om or k1om)
endif

# Force optimization to -O2 in case the kernel was configured to use
# -Os. The main reason is pretty dumb -- -Os has a warning -O2 doesn't,
# and we compile with -Werror internally. Another reason is that -O2 is
# what we're used to in terms of validation and performance analysis. We
# should probably get rid of this, though.
subdir-ccflags-y += -O2

# Makes it easy to inject "-Werror" from the environment
subdir-ccflags-y += $(KERNWARNFLAGS)

# COSAI BEGIN BLOCK
subdir-ccflags-y += -I$(M)/../cosai
# COSAI END BLOCK -

# Pass some ifdefs to configure build a little
#subdir-ccflags-y += -DLBP_PROTOCOL_ON
#subdir-ccflags-y += -DRDK_SUPPORT

# Bake some information about who built the module(s), and what version
# of the source code they started with. Possibly useful during debug.
subdir-ccflags-y += -DBUILD_NUMBER=\"'$(VCASS_BUILDNO)'\"
subdir-ccflags-y += -DBUILD_BYWHOM=\"'$(VCASS_BUILTBY)'\"
subdir-ccflags-y += -DBUILD_ONDATE=\"'$(VCASS_BUILTON)'\"
subdir-ccflags-y += -DBUILD_VERSION=\"'$(or $(VCASS_VERSION),0.0) ($(VCASS_BUILTBY))'\"

# Code common with the host mustn't use CONFIG_M[LK]1OM directly.
# But of course it does anyway. Arrgh.
subdir-ccflags-$(CONFIG_ML1OM) += -DVCA_IS_L1OM
subdir-ccflags-$(CONFIG_MK1OM) += -DVCA_IS_K1OM
ifeq ($(VCA_CARD_ARCH),l1om)
subdir-ccflags-y += -DVCA_IS_L1OM -DCONFIG_ML1OM
endif
ifeq ($(VCA_CARD_ARCH),k1om)
subdir-ccflags-y += -DVCA_IS_K1OM -DCONFIG_MK1OM
endif

# Compile-time personality.  Node code uses _VCA_SCIF_; host code uses
# HOST/USE_VCONSOLE.  This must not be inferred from CONFIG_X86_VCAPCI because
# Ubuntu kernels do not define that Intel-private configuration option.
ifeq ($(VCA_BUILD_ROLE),node)
subdir-ccflags-y += -D_VCA_SCIF_
else
subdir-ccflags-y += -DHOST -DUSE_VCONSOLE
endif

# always set? what's this thing's purpose?
subdir-ccflags-y += -D__LINUX_GPL__ -D_MODULE_SCIF_

subdir-ccflags-y += -I$(M)/include
subdir-ccflags-y += -include $(M)/vca/include/vca_linux_6x_compat.h

# BlockIO front-end has been ported to Linux 6.x blk-mq.
# Keep it enabled for the v9 BlockIO test build.
VCA_BUILD_BLOCKIO ?= 1
subdir-ccflags-y += -DVCA_BUILD_BLOCKIO=$(VCA_BUILD_BLOCKIO)


subdir-ccflags-y += -fstack-protector -O2 -D_FORTIFY_SOURCE=2 -Wformat
ldflags-y += -z noexecstack -z relro -z now

# Build only the modules that have a useful role on each side of the
# VCA link.  The node must include CSA and the VCA virtio stack: VOP creates
# child devices whose drivers are supplied by those modules.
ifeq ($(VCA_BUILD_ROLE),node)
obj-m += vca/bus/
obj-m += vca/vca_csa/
obj-m += vca/vca_virtio/
obj-m += vca/vop/
ifeq ($(VCA_BUILD_BLOCKIO),1)
obj-m += vca/blockio/
endif
obj-m += plx87xx.o
obj-m += vca/plx87xx_dma/
else
obj-m += vca/bus/
obj-m += vca/vca_csm/
obj-m += vca/vca_mgr/
obj-m += vca/vca_mgr_extd/
obj-m += vca/vca_csa/
obj-m += vca/vca_virtio/
obj-m += vca/vop/
ifeq ($(VCA_BUILD_BLOCKIO),1)
obj-m += vca/blockio/
endif
obj-m += plx87xx.o
obj-m += vca/plx87xx_dma/
endif

plx87xx-objs :=
plx87xx-objs += vca/plx87xx/plx_main.o
plx87xx-objs += vca/plx87xx/plx_boot.o
plx87xx-objs += vca/plx87xx/plx_hw.o
plx87xx-objs += vca/plx87xx/plx_debugfs.o
plx87xx-objs += vca/plx87xx/plx_procfs.o
plx87xx-objs += vca/plx87xx/plx_intr.o
plx87xx-objs += vca/plx87xx/plx_alm.o
plx87xx-objs += vca/plx87xx/plx_lbp.o
ifeq ($(VCA_BUILD_BLOCKIO),1)
plx87xx-objs += vca/plx87xx/plx_hw_ops_blockio.o
endif
plx87xx-objs += vca/plx87xx/plx_hw_ops_vca_mgr.o
plx87xx-objs += vca/plx87xx/plx_hw_ops_vca_mgr_extd.o
plx87xx-objs += vca/plx87xx/plx_hw_ops_vca_csa.o
plx87xx-objs += vca/plx87xx/plx_hw_ops_vca_csm.o
plx87xx-objs += vca/plx87xx/plx_hw_ops_vop.o

plx87xx_dma-objs :=
plx87xx_dma-objs += vca/plx87xx_dma/plx_pci.o
plx87xx_dma-objs += vca/plx87xx_dma/plx_dma.o
plx87xx_dma-objs += vca/plx87xx_dma/plx_debugfs.o

version-le = $(shell printf '%s\n' $(1) | sort -t. -k 1,1n -k 2,2n -k 3,3n -k 4,4n -c >/dev/null 2>&1 && echo t)
ifeq ($(call version-le, 2.6.23 $(KERNELRELEASE)),t)
ccflags-y += $(vca-cflags)
else
$(error building against kernels <= 2.6.23 is broken)
endif
