# VCA2 card-side load ordering.  Unlike the host, the node must load vca_csa.
softdep plx87xx pre: vop_bus vca_csm_bus vca_mgr_bus vca_mgr_extd_bus vca_csa_bus vca_virtio vca_virtio_ring vca_vringh vca_virtio_net vca_csa vcablkfe vcablk_bckend vop plx87xx_dma
